on: [workflow_dispatch]

name: AzureLoginSample

jobs:

  build-and-deploy:
    runs-on: self-hosted
    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - run: |
        cp -R /Users/balaga-gayatri/actions-runner /Users/balaga-gayatri/action-runner-copy 
        sleep 1000
        az vm list


#  creds_client_id: '8751f16d-d2bc-49ea-8c19-1fd2b19b22'
