on: [push]

name: AzureLoginSample

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: balaga-gayatri/login@dev_creds
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        # creds_client_id: ${{ secrets.CLIENT_ID }}
        # creds_client_secret: ${{ secrets.CLIENT_SECRET }}
        # creds_tenant_id: ${{ secrets.TENANT_ID }}
        # creds_subscription_id:  ${{ secrets.SUBSCRIPTION_ID }}

    - run: |
        az vm list


#  creds_client_id: '8751f16d-d2bc-49ea-8c19-1fd2b19b22'